name: FactionsPlus
author: FactionsPlus Team
main: FactionsPlus/FactionsMain
api: 2.0.0
version: 1.0#Beta
commands:
 f:
  permission: factions.command
  description: FactionsPlus Command
  usage: /f [help]
permissions:
    factions.command:
      default: true
      description: FactionsPlus command
